### ISSUE TITLE
Automate picking up reader names and placing them in the cli help strings

### ISSUE THREAD

**Issue by sherjeelshabih** [FAIRmat-NFDI/pynxtools#161]
I think we can all benefit from having the click help text be automatically picked up. We already automatically pick up what readers we can use from the CLI. This just does not get propagated to the text.

@domna @RubelMozumder @mkuehbach @sanbrock @lukaspie 
Is there some other part of the code that could benefit from picking up the readers based on the available ones in the dataconverter/readers/ subfolder? I'm just asking in case I am missing quite an obvious one.

**Comment by domna** [comment]
[mkdocs-click](https://pypi.org/project/mkdocs-click/) could help here. But I think for this we need to decide whether we want to use something like mkdocs for a proper documentation here. We could use [readthedocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html) for deployment (or simply compile to gh pages).
