### ISSUE TITLE
Pluginise mpes reader

### ISSUE THREAD

**Issue by lukaspie** [FAIRmat-NFDI/pynxtools#234]
We could also think about having a generic igor reader that we can then map for the different techniques.

**Comment by domna** [comment]
# Plan

- [ ] Move existing reader into the mpes reader
- [ ] Extend the general reader and rework mpes
- [ ] Pluginise mpes reader

**Comment by domna** [comment]
Igor support in https://github.com/FAIRmat-NFDI/pynxtools-mpes/issues/2
