### ISSUE TITLE
Rework the CLI interface and support folder reading

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#238]
I think it would be helpful to use the dataconverter like this: `dataconverter --reader my_reader --nxdl NXtest FILENAME FILENAME FILENAME`, i.e., without the `--input-file`. This should be supported be click (there is a lot offered for convenience file interaction, so I think we can also use more of what click supplies). Ideally, we would make this backwards compatible such that `--input-file` is still supported.

Also being able to read complete folders would be useful, i.e., the reader would then read any files inside that folder and/or it is possible to design readers which work on folders directly. This is useful for config/data file combinations.

**Comment by rettigl** [comment]
Sounds like a good idea. For the folder idea, I think this we can leave to the command line, no? i.e. dataconverter FOLDER/*.* should work if we support multiple files.

**Comment by RubelMozumder** [comment]
I also realized the same for `--input-file` option, when running `sts` reader from the command line it is really cumbersome when one needs to use it `--input-file` for every files. But adding another feature for the folder would be awesome.

Do you think: something like 
`--input-file [list of files]` and 
`--file-folder <name of the folder>`

**Comment by sherjeelshabih** [comment]
I like this idea too. It seems to fit better to the idea as well. We get --params with hyphens and files/folders as many without any hyphens. I'll add this for the JOSS release.
