### ISSUE TITLE
Create plugin documentation

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#247]
We should have a proper documentation of our plugins:

- [x] Add a list of plugins we maintain to README
- [x] Link to the pynxtools-plugin gh topic in the README
- [x] Write a tutorial/how-to on dealing with plugins and how to create a plugin/reader (based on https://github.com/FAIRmat-NFDI/pynxtools-plugin-template)
- [x] Add a list of extra installs

This should also be reflected in the https://github.com/FAIRmat-NFDI/pynxtools-plugin-template, i.e.,
- [ ] Link to main repo
- [ ]Link to pynxtools-plugin topic

- [x] apm
- [x] em
- [x] xps
- [x] mpes
- [x] sts
- [ ] ivtemp
- [x] opt

**Comment by RubelMozumder** [comment]
#231 resolved here!
