### ISSUE TITLE
Required fields under optional groups end up in required generated template

### ISSUE THREAD

**Issue by sherjeelshabih** [FAIRmat-NFDI/pynxtools#266]
This is discussed a bit in #257. Only fields that will break the reader's functionality if not provided should be displayed with the required flag in generate-template.

              When I use the `--required` flag it also reports fields which are under optional groups, which we should not output here. I would say that we should only require those which are strictly required.
              
_Originally posted by @domna in https://github.com/FAIRmat-NFDI/pynxtools/issues/257#issuecomment-1959611191_

**Comment by lukaspie** [comment]
@sherjeelshabih @domna where do we stand on this? Is this solved by the new nexus tree structure?

**Comment by domna** [comment]
> @sherjeelshabih @domna where do we stand on this? Is this solved by the new nexus tree structure?

Yes, this is fixed with the new algorithm.
