### ISSUE TITLE
Fix typos of NXroot elements in pynxtools

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/pynxtools#290]

**Comment by mkuehbach** [comment]
https://manual.nexusformat.org/classes/base_classes/NXroot.html#nxroot defines specifically named attributes which pynxtools (tested via pynxtools-apm) auto-decorates, however:

- [ ] Attributes named "File_*" have to be lower-case

**Comment by mkuehbach** [comment]
@domna mentioned and I confirm H5Web capitalizes attribute names which mislead me but "convenience feature" makes inspections of compliance with schemas more difficult, maybe a topic for the H5Web developers?

**Comment by domna** [comment]
Closing this as this requires no action in pynxtools
