### ISSUE TITLE
Correctly use the extends keywords for applications definitions

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#35]
If an application definition uses the extends keyword the reader only checks the fields from the extending appdef and not the fields of the class which is extended. This should be supported ideally for base classes and application definitions.

There is a test in the branch https://github.com/nomad-coe/nomad-parser-nexus/tree/appdef_extends which checks the behaviour (currently failing test_inheritance).

**Comment by lukaspie** [comment]
Closed as completed by https://github.com/FAIRmat-NFDI/pynxtools/pull/339
