### ISSUE TITLE
Adapt to new NOMAD type system

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#353]
https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/1814

- [ ] Adapt changes of the plain type system
- [ ] Reactivate nexus ellipsometry test
- [ ] Make separate PR to 1814 (or commit there directly) in discussion with Theodore

**Comment by lukaspie** [comment]
Closed as fixed by https://gitlab.mpcdf.mpg.de/nomad-lab/nomad-FAIR/-/merge_requests/1938
