### ISSUE TITLE
Make pynxtools-raman (Repository and Reader)

### ISSUE THREAD

**Issue by mkuehbach** [FAIRmat-NFDI/pynxtools#356]
- [x] Get Example Data from Tamas (~0d)
- [x] Make pynxtools-raman repository (0.5d)
- [x] Make pynxtools-raman reader (1d)
- [x] Create NeXus File without warnings from Example Data (0.75d)

**Comment by lukaspie** [comment]
Can this be closed @RonHildebrandt as pynxtools-raman exists?

**Comment by RonHildebrandt** [comment]
Yea. The Raman plugin in is here:
https://github.com/FAIRmat-NFDI/pynxtools-raman/pull/1, should pass the CI/CD as soon as the the the submodules are updated in pynxtools
