### ISSUE TITLE
Enlarge the Error Raise in yaml2nxdl

### ISSUE THREAD

**Issue by aalbino2** [FAIRmat-NFDI/pynxtools#41]
I realized that many features in yaml are not actually checked when creating an nxdl, e. g. if one mistypes the units, no error is raised.

We should address this soon

**Comment by domna** [comment]
Yes, there is also an related issue that if there is a units attribute in a base class and it is not explicitly written in a base class the reader throws a warning that an attribute w/o documentation is written. Our solution in NXmpes was to just write the units attributes in the appdef again to suppress this warnings. Probably, this is not only related to units but also throws warnings for attributes in general.

**Comment by shabihsherjeel** [comment]
> Yes, there is also an related issue that if there is a units attribute in a base class and it is not explicitly written in a base class the reader throws a warning that an attribute w/o documentation is written. Our solution in NXmpes was to just write the units attributes in the appdef again to suppress this warnings. Probably, this is not only related to units but also throws warnings for attributes in general.

I think this is actually separate from what @aalbino2 mentions here. What you mention is actually related to the way we handle inheritance in the dataconverter. We can meet for a meeting and put these thoughts together. I want to handle this once correctly. I can explain you in more detail over zoom why it works how it does currently and what I am planning to do to sort this out.

**Comment by aalbino2** [comment]
Please pin me when you will discuss this @shabihsherjeel @domna, thank you.

And, yes, Sherjeel is right, I was talking about catching more and more possible errors contained in the yaml file of an app def or base class
