### ISSUE TITLE
Dataconverter linking unset field fails

### ISSUE THREAD

**Issue by sherjeelshabih** [FAIRmat-NFDI/pynxtools#67]
If a field, /entry/A, is not set in the template and we try to link to it from another entry, /entry/B, using the link functionality, the Writer fails. Instead, this should check if /entry/A is set or not before trying to write the link to it in /entry/B.

@Arora0 found this bug while working on the MPES reader.

**Comment by lukaspie** [comment]
I think this is resolved right?
