### ISSUE TITLE
Allow writing of `:` in yaml

### ISSUE THREAD

**Issue by domna** [FAIRmat-NFDI/pynxtools#81]
With #78 colons need to be escaped with quotes in yaml (`':'`) and are automatically added when converting `nxdl` to `yaml`. Eventually, writing `:` should be allowed for convenience. This should also be allowed by PyYAML as long as the line is correctly enclosed with quotes or piped.

**Comment by RubelMozumder** [comment]
This is resolved with the current version of nyaml converter. @domna I will close it If you do not have any concern.

**Comment by domna** [comment]
ok
